### ISSUE TITLE
Ability to have 2 separate games on the same server

### ISSUE THREAD

**Issue by magroader** [lilserf/botc_mover#22]
Depends on #5

We're getting to the point where we are almost full up for a single game of BotC, with around 12-13 players. If we eventually hit 16 players, that's sort of 1 too many (although travelers can alleviate that) and there's a LOT of crosstalk. It may very well be better, in such a case, to split up into 2 groups (8 players and 7 players, or more).

In order to facilitate this, the mover bot would need some extra sauce:

Assuming there will be 2 separate #botc_mover channels, and that each of those represents its own game. For each #botc_mover channel:
* It needs to be able to set what the nighttime category is (e.g. `!set nightcategory <id or string>`)
* It should be able to figure out what the daytime category is, as the #botc_mover channel is already in that category, so no extra command likely required there.
* It needs to be able to set what the Current Storyteller Role is (e.g. `!set strole <id or string>`)
* It needs to be able to set what the Current Player Role is (e.g. `!set playerrole <id or string>`)

**Comment by lilserf** [comment]
A version of this is now active!
