### ISSUE TITLE
Persistent storage features

### ISSUE THREAD

**Issue by lilserf** [lilserf/botc_mover#5]
- Allow a guild to specify the category, channel, and role names by storing guild info in a DB somewhere

**Comment by magroader** [comment]
I assume a guild is also known as a server?

As per #22, I think rather than storing this info per guild, it should store it per guild/daytime category. That way a single guild can run more than 1 game.

**Comment by magroader** [comment]
Or maybe guild/instance, and instances can just so happen to line up with daytime categories by default

**Comment by lilserf** [comment]
I’ve got a start of a MongoDb setup which is basically just a collection of JSON objects so then it’s basically up to us how we want to code up the bot commands

**Comment by magroader** [comment]
Would the DB lookup be very fast? I'm wondering if the script should cache the DB lookup results locally for performance. Not sure how that works.

**Comment by lilserf** [comment]
This is implemented, yay
